### ISSUE TITLE
False positive new version notification

### ISSUE THREAD

**Issue by Skriptach** [gladiusio/gladius-manager-ui#95]
I have Win 0.7.0 version installed on my PC. Which is last at the moment. And notification popup on launch of the app.
![image](https://user-images.githubusercontent.com/390735/50258287-e3c9c480-03f6-11e9-8133-fafa28226705.png)

**Comment by code-merc** [comment]
We actually released a patch on tuesday [here](https://github.com/gladiusio/gladius-node/releases/tag/0.7.1)
